name: "[main] Build & Release"

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  Build:
    name: Build for Windows, Linux, and Mac
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      # Install Node.js normally on macOS & Windows
      - name: Install Node.js 📥
        if: ${{ !contains(matrix.runs-on, 'ubuntu') }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
          cache: "npm"

      # Install full unstripped Node.js on Linux
      - name: Install unstripped Node.js on Linux 🐧
        if: contains(matrix.runs-on, 'ubuntu')
        run: |
          curl -fsSL https://nodejs.org/dist/v20.15.1/node-v20.15.1-linux-x64.tar.xz -o node.tar.xz
          tar -xf node.tar.xz
          echo "$PWD/node-v20.15.1-linux-x64/bin" >> $GITHUB_PATH
          echo "Using custom Node path: $(which node)"
          node -v

      - name: Install dependencies 📦
        run: npm ci

      - name: Build Binaries 🔨
        shell: bash
        run: |
          if [[ "${{ matrix.runs-on }}" == "ubuntu-latest" ]]; then
            npm run build-ubuntu-latest
          elif [[ "${{ matrix.runs-on }}" == "windows-latest" ]]; then
            npm run build-windows-latest
          elif [[ "${{ matrix.runs-on }}" == "macos-latest" ]]; then
            npm run build-macos-latest
          fi

      - name: Upload Build Artifact 📤
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.runs-on }}
          path: ./compiled/

  Release:
    name: Create Release with Auto-Version 🚀
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./compiled/
          merge-multiple: true

      - name: Install GitHub CLI (gh)
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get latest version tag and compute new version
        id: get_tag
        run: |
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="v$major.$minor.$patch"

          echo "New version: $new_version"
          echo "new_tag=$new_version" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        run: |
          gh release create "${{ steps.get_tag.outputs.new_tag }}" \
            --title "Release ${{ steps.get_tag.outputs.new_tag }}" \
            --generate-notes \
            --latest \
            ./compiled/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
